"""Canonical feature groups and labels used by the prompt analytics tools.

This module defines the feature taxonomy consumed by the plotting and
summary code under :mod:`clean_data.prompt`.  Keeping the mapping in one
place ensures the CLI, reporting scripts, and documentation highlight the
same viewer attributes and survey responses.
"""

from __future__ import annotations

from typing import Dict, Sequence

# ---------------------------------------------------------------------------
# Feature definitions mirroring prompt_builder.py
# ---------------------------------------------------------------------------

PROMPT_FEATURE_GROUPS: Dict[str, Sequence[str]] = {
    # Demographics
    "age": ["age"],
    "gender": ["gender", "q26"],
    "race_ethnicity": ["race", "ethnicity", "q29"],
    "city": ["city", "city_name"],
    "state": ["state", "state_residence", "state_name", "inputstate"],
    "county": ["county", "county_name"],
    "zip3": ["zip3"],
    "education": ["education", "educ", "education_level", "college_desc"],
    "college": ["college"],
    "household_income": ["q31", "income", "household_income"],
    "employment_status": ["employment_status", "employment", "labor_force", "employ"],
    "occupation": ["occupation"],
    "marital_status": ["marital_status", "married"],
    "children_in_household": ["children_in_house", "kids_household", "child18"],
    "household_size": ["household_size"],
    "religion": ["religion", "relig_affiliation", "religious_affiliation", "religpew"],
    "religious_attendance": ["relig_attend", "church_attend", "service_attendance", "pew_religimp"],
    "veteran": ["veteran", "military_service"],
    # Politics
    "party_identification": ["pid1", "party_id", "party_registration"],
    "party_lean": ["pid2", "party_id_lean", "party_lean"],
    "ideology": ["ideo1", "ideo2", "ideology"],
    "political_interest": ["pol_interest", "interest_politics", "political_interest"],
    "vote_2016": ["vote_2016", "presvote16post"],
    "vote_2020": ["vote_2020", "presvote20post"],
    "vote_2024": ["vote_2024", "vote_intent_2024", "vote_2024_intention"],
    "trump_approval": [
        "trump_approve",
        "trump_job_approval",
        "q5_2",
        "Q5_a",
        "Q5_a_W2",
        "political_lead_feels_2",
    ],
    "biden_approval": [
        "biden_approve",
        "biden_job_approval",
        "q5_5",
        "Q5_b",
        "Q5_b_W2",
        "political_lead_feels_5",
    ],
    "civic_engagement": ["civic_participation", "volunteering", "civic_activity"],
    # Minimum wage attitudes
    "minwage_text_r_w1": ["minwage_text_r_w1"],
    "minwage_text_r_w2": ["minwage_text_r_w2"],
    "minwage_text_r_w3": ["minwage_text_r_w3"],
    "minwage_text_w1": ["minwage_text_w1"],
    "minwage_text_w2": ["minwage_text_w2"],
    "mw_index_w1": ["mw_index_w1"],
    "mw_index_w2": ["mw_index_w2"],
    "minwage15_w1": ["minwage15_w1"],
    "minwage15_w2": ["minwage15_w2"],
    "mw_support_w1": ["mw_support_w1"],
    "mw_support_w2": ["mw_support_w2"],
    "minwage_importance": ["minwage_importance"],
    "minwage_priority": ["minwage_priority"],
    # Media habits
    "freq_youtube": ["freq_youtube", "q77", "Q77", "youtube_freq", "youtube_freq_v2"],
    "binge_youtube": ["binge_youtube", "youtube_time"],
    "favorite_channels": ["q8", "fav_channels"],
    "popular_channels_followed": ["q78", "popular_channels"],
    "media_diet": ["media_diet"],
    "news_consumption": ["news_consumption"],
    "news_sources": ["news_sources"],
    "news_sources_top": ["news_sources_top"],
    "news_frequency": ["news_frequency", "newsint"],
    "platform_use": ["platform_use"],
    "social_media_use": ["social_media_use"],
    "news_trust": [
        "news_trust",
        "trust_majornews_w1",
        "trust_localnews_w1",
        "trust_majornews_w2",
        "trust_localnews_w2",
        "trust_majornews_w3",
        "trust_localnews_w3",
    ],
    # Gun policy attitudes
    "gun_ownership": ["gun_own", "gunowner", "owns_gun"],
    "right_to_own_importance": ["right_to_own_importance"],
    "assault_ban": ["assault_ban"],
    "handgun_ban": ["handgun_ban"],
    "concealed_safe": ["concealed_safe"],
    "stricter_laws": ["stricter_laws"],
    "gun_index": ["gun_index"],
    "gun_index_2": ["gun_index_2"],
    "gun_enthusiasm": ["gun_enthusiasm"],
    "gun_importance": ["gun_importance"],
    "gun_priority": ["gun_priority"],
    "gun_policy": ["gun_policy"],
    "gun_identity": ["gun_identity"],
}

DEMOGRAPHIC_FEATURE_KEYS = [
    "age",
    "gender",
    "race_ethnicity",
    "city",
    "state",
    "county",
    "zip3",
    "education",
    "college",
    "household_income",
    "employment_status",
    "occupation",
    "marital_status",
    "children_in_household",
    "household_size",
    "religion",
    "religious_attendance",
    "veteran",
]

FEATURE_LABELS: Dict[str, str] = {
    "age": "Viewer age",
    "gender": "Gender",
    "race_ethnicity": "Race / ethnicity",
    "city": "City",
    "state": "State",
    "county": "County",
    "zip3": "ZIP3 prefix",
    "education": "Education level",
    "college": "College graduate flag",
    "household_income": "Household income bracket",
    "employment_status": "Employment status",
    "occupation": "Occupation text",
    "marital_status": "Marital status",
    "children_in_household": "Children in household flag",
    "household_size": "Household size",
    "religion": "Religious affiliation",
    "religious_attendance": "Religious service attendance",
    "veteran": "Veteran status",
    "party_identification": "Party identification",
    "party_lean": "Party lean",
    "ideology": "Political ideology",
    "political_interest": "Political interest",
    "vote_2016": "2016 vote recall",
    "vote_2020": "2020 vote recall",
    "vote_2024": "2024 vote intention",
    "trump_approval": "Trump approval",
    "biden_approval": "Biden approval",
    "civic_engagement": "Civic engagement",
    "minwage_text_r_w1": "Minimum wage stance (wave 1, inferred)",
    "minwage_text_r_w2": "Minimum wage stance (wave 2, inferred)",
    "minwage_text_r_w3": "Minimum wage stance (wave 3, inferred)",
    "minwage_text_w1": "Minimum wage stance (wave 1, survey)",
    "minwage_text_w2": "Minimum wage stance (wave 2, survey)",
    "mw_index_w1": "Minimum wage support index (wave 1)",
    "mw_index_w2": "Minimum wage support index (wave 2)",
    "minwage15_w1": "$15 minimum wage support (wave 1)",
    "minwage15_w2": "$15 minimum wage support (wave 2)",
    "mw_support_w1": "Supports wage increase (wave 1)",
    "mw_support_w2": "Supports wage increase (wave 2)",
    "minwage_importance": "Minimum wage importance",
    "minwage_priority": "Minimum wage priority",
    "freq_youtube": "YouTube watch frequency code",
    "binge_youtube": "Binge-watches YouTube flag",
    "favorite_channels": "Favorite channels text",
    "popular_channels_followed": "Popular channels followed",
    "media_diet": "Media diet description",
    "news_consumption": "News consumption description",
    "news_sources": "News sources list",
    "news_sources_top": "Top news sources",
    "news_frequency": "News consumption frequency",
    "platform_use": "Platform usage summary",
    "social_media_use": "Social media use",
    "news_trust": "News trust level",
    "gun_ownership": "Gun ownership flag",
    "right_to_own_importance": "Right to own importance",
    "assault_ban": "Supports assault weapons ban",
    "handgun_ban": "Supports handgun ban",
    "concealed_safe": "Believes concealed carry is safe",
    "stricter_laws": "Supports stricter gun laws",
    "gun_index": "Gun index",
    "gun_index_2": "Gun index (alternate)",
    "gun_enthusiasm": "Gun enthusiasm",
    "gun_importance": "Gun importance",
    "gun_priority": "Gun policy priority",
    "gun_policy": "Gun policy stance",
    "gun_identity": "Gun identity strength",
}
