name: Clean Data Suite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clean-data:
    runs-on: ubuntu-latest

    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      GRAIL_SOURCE_DATASET: ${{ secrets.GRAIL_SOURCE_DATASET }}
      GRAIL_ISSUE_REPOS: ${{ secrets.GRAIL_ISSUE_REPOS }}
      GRAIL_PUSH_TO_HUB: ${{ secrets.GRAIL_PUSH_TO_HUB }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: development/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development/requirements-dev.txt

      - name: Run clean data suite
        run: scripts/run-clean-data-suite.sh
