name: Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: development/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development/requirements-dev.txt

      - name: Build Sphinx documentation
        env:
          PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}
        run: |
          rm -rf docs/_build/html
          sphinx-build -b html -n -W --keep-going docs docs/_build/html

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html
          path: docs/_build/html
