name: Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: development/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r development/requirements-dev.txt

      - name: Docstring consistency check (src/visualization)
        run: python scripts/check_docstrings.py src/visualization

      - name: Build Sphinx docs (nitpicky, warnings as errors)
        env:
          SPHINX_NITPICKY: "1"
          SPHINX_ENABLE_INTERSPHINX: "0"
        run: |
          python -m sphinx -W -b html docs docs/_build/html

      - name: Upload docs HTML
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html
          if-no-files-found: warn

